---
parser: babel-eslint
parserOptions:
  parser: babel-eslint
  ecmaVersion: 6
  sourceType: module
env:
  browser: true
  jest/globals: true
extends:
  - standard
  - standard-react
plugins:
  - html
  - jest
